channels:
  - conda-forge
dependencies:
  - h5py
  - highfive
  - xdmfwrite_highfive
  - xdmfwrite_h5py
  - gmatelastic
  - gmatnonlinearelastic
  - gmatelastoplastic
  - gmatelastoplasticfinitestrainsimo
  - gmatelastoplasticqpot
  - python-gmatelastic
