channels:
  - conda-forge
dependencies:
  # dependencies
  - xtensor
  - eigen

  # optional dependencies
  - xsimd

  # build tools
  - cmake
  - ninja
  - setuptools_scm

  # Python API
  - python
  - numpy
  - pybind11
  - xtensor-python
  - pyxtensor

  # to run tests
  - catch2
  - gmatelastic
  - gmatelastoplasticqpot

  # to run examples
  - h5py
  - highfive
  - xdmfwrite_highfive
  - xdmfwrite_h5py
  - gmatelastic
  - gmatnonlinearelastic
  - gmatelastoplastic
  - gmatelastoplasticfinitestrainsimo
  - gmatelastoplasticqpot
  - python-gmatelastic

