channels:
- conda-forge
dependencies:
- catch2
- cmake
- eigen
- gmatelastic
- gmatelastoplastic
- gmatelastoplasticfinitestrainsimo
- gmatelastoplasticqpot
- qpot <0.12.0 # remove when "gmatelastoplasticqpot" is updated
- gmatnonlinearelastic
- h5py
- highfive
- ninja
- numpy
- pybind11
- python
- python-gmatelastic
- scikit-build
- setuptools_scm
- xdmfwrite_h5py
- xdmfwrite_highfive
- xsimd
- xtensor
- xtensor-python
